version: '3'

services:
   messaging-server:
      image: nats
      logging:
        driver: none
   tor-proxy:
      image: osminogin/tor-simple
      logging:
        driver: none
   database:
      image: mongo
      logging:
        driver: none
   database_seeder:
      build:
         context: .
         dockerfile: Dockerfile-mongoseeder
      logging:
         driver: none
      depends_on:
         - database
   database-ui:
      image: mongo-express
      logging:
        driver: none
      environment:
         ME_CONFIG_MONGODB_SERVER: database
      ports:
        - 15001:8081
   crawler:
      image: trandoshan-io/crawler
      restart: unless-stopped
      depends_on:
         - messaging-server
         - tor-proxy
   scheduler:
      image: trandoshan-io/scheduler
      restart: unless-stopped
      depends_on:
         - messaging-server
         - api
   persister:
      image: trandoshan-io/persister
      restart: unless-stopped
      depends_on:
         - messaging-server
         - database
   api:
      image: trandoshan-io/api
      restart: unless-stopped
      depends_on:
        - database
        - messaging-server
      ports:
        - 15002:8080