version: '3'

services:
   rabbitmq:
      build:
         context: .
         dockerfile: Dockerfile-rabbitmq
      ports:
         - 15000:15672
   database:
      image: mongo:latest
   database-ui:
      image: mongo-express:latest
      environment:
         ME_CONFIG_MONGODB_SERVER: database
      ports:
        - 15001:8081
   crawler:
      image: trandoshan-io/crawler
      restart: unless-stopped
      depends_on:
         - rabbitmq
   scheduler:
      image: trandoshan-io/scheduler
      restart: unless-stopped
      depends_on:
         - rabbitmq
   persister:
      image: trandoshan-io/persister
      restart: unless-stopped
      depends_on:
         - rabbitmq
         - database
