version: '3'

services:
   messaging-server:
      image: nats
      logging:
        driver: none
   tor-proxy:
      image: osminogin/tor-simple
      logging:
        driver: none
   elasticsearch:
      image: elasticsearch:7.5.1
      logging:
         driver: none
      environment:
         - discovery.type=single-node
         - JAVA_OPTS=-Xms2g -Xmx2g
   kibana:
      image: kibana:7.5.1
      logging:
        driver: none
      depends_on:
         - elasticsearch
      ports:
         - 15004:5601
   crawler:
      image: trandoshanio/crawler
      restart: unless-stopped
      environment:
         - TOR_PROXY=tor-proxy:9050
         - NATS_URI=nats://derek:pass@messaging-server:4222
         - FORBIDDEN_CONTENT_TYPES=application/octet-stream
         - USER_AGENT=trandoshan-io/crawler
      depends_on:
         - messaging-server
         - tor-proxy
   scheduler:
      image: trandoshanio/scheduler
      restart: unless-stopped
      environment:
         - NATS_URI=nats://derek:pass@messaging-server:4222
         - API_URI=http://api:8080
      depends_on:
         - messaging-server
         - api
   persister:
      image: trandoshanio/persister
      volumes:
        - resources:/resources
      restart: unless-stopped
      environment:
         - NATS_URI=nats://derek:pass@messaging-server:4222
         - STORAGE_PATH=/resources
         - ELASTICSEARCH_URL=http://elasticsearch:9200
      depends_on:
         - messaging-server
   api:
      image: trandoshanio/api
      restart: unless-stopped
      environment:
         - ELASTICSEARCH_URL=http://elasticsearch:9200
      depends_on:
         - elasticsearch
         - messaging-server
      ports:
        - 15002:8080
#   feeder:
#      image: trandoshanio/feeder
#      environment:
#         - NATS_URI=nats://derek:pass@messaging-server:4222
#         - INITIAL_URI=something_here
#      depends_on:
#         - messaging-server
   dashboard:
      image: trandoshanio/dashboard
      depends_on:
         - api
      ports:
         - 15003:80
volumes:
  resources:
    driver: local