version: '3'

services:
   rabbitmq:
      build:
         context: .
         dockerfile: Dockerfile-rabbitmq
      logging:
        driver: none
      ports:
         - 15000:15672
   tor-proxy:
      image: osminogin/tor-simple
      logging:
        driver: none
   database:
      image: mongo
      logging:
        driver: none
   database-ui:
      image: mongo-express
      logging:
        driver: none
      environment:
         ME_CONFIG_MONGODB_SERVER: database
      ports:
        - 15001:8081
   crawler:
      image: trandoshan-io/crawler
      restart: unless-stopped
      depends_on:
         - rabbitmq
         - tor-proxy
   scheduler:
      image: trandoshan-io/scheduler
      restart: unless-stopped
      depends_on:
         - rabbitmq
   persister:
      image: trandoshan-io/persister
      restart: unless-stopped
      depends_on:
         - rabbitmq
         - database
   api:
      image: trandoshan-io/api
      restart: unless-stopped
      depends_on:
        - database
        - rabbitmq
      ports:
        - 15002:8080